In [1]:
import nltk
import pandas as pd
nltk.download('vader_lexicon')
from pymongo import MongoClient

[nltk_data] Downloading package vader_lexicon to
[nltk_data]     /home/dishant/nltk_data...
[nltk_data]   Package vader_lexicon is already up-to-date!

In [2]:
from nltk.sentiment.vader import SentimentIntensityAnalyzer
sid = SentimentIntensityAnalyzer()

In [3]:
## mongoDB implementation
# build a new client instance for MongoClient
mongo_client = MongoClient('localhost', 27017)

# create new database and client collection
db = mongo_client.crypto
col = db.bitcoin_tweets

df = pd.DataFrame(list(col.find()))
df.head()

ServerSelectionTimeoutError: localhost:27017: [Errno 111] Connection refused, Timeout: 30s, Topology Description: <TopologyDescription id: 6109bd800ce4c9070992d7ab, topology_type: Single, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 111] Connection refused')>]>

In [4]:


df = pd.read_csv("bitcoin_tweets.csv")
df.head()

,UserName,Handle,Timestamp,Text,Emojis,Comments,Likes,Retweets
0,Erin Malone,@ErinEMalone,2021-07-18T23:23:20.000Z,"1. 10 weeks ago, I joined the \n@lightning\n n...",NaN,76,487,1.9K
1,Linkamus ₿ ∞/21M,@VersusTheMan,2021-07-18T23:02:42.000Z,I've bought as much #bitcoin as I can possibly...,NaN,153,37,718
2,Ben Armstrong,@Bitboy_Crypto,2021-07-18T21:50:17.000Z,The vast majority of people are crypto-aware. ...,NaN,97,113,1K
3,AirdropStar,@AirdropStario,2021-07-18T20:52:26.000Z,YUKISwap Airdrop \n\n Task: Up to 40...,NaN,170,1.7K,1.4K
4,Jason A. Williams “Parabolic Guy”,@GoingParabolic,2021-07-18T20:50:31.000Z,Time to spartan up. They are coming for your #...,NaN,75,39,524

In [5]:
df = df.drop(columns = ["Emojis"])
df.head()

,UserName,Handle,Timestamp,Text,Comments,Likes,Retweets
0,Erin Malone,@ErinEMalone,2021-07-18T23:23:20.000Z,"1. 10 weeks ago, I joined the \n@lightning\n n...",76,487,1.9K
1,Linkamus ₿ ∞/21M,@VersusTheMan,2021-07-18T23:02:42.000Z,I've bought as much #bitcoin as I can possibly...,153,37,718
2,Ben Armstrong,@Bitboy_Crypto,2021-07-18T21:50:17.000Z,The vast majority of people are crypto-aware. ...,97,113,1K
3,AirdropStar,@AirdropStario,2021-07-18T20:52:26.000Z,YUKISwap Airdrop \n\n Task: Up to 40...,170,1.7K,1.4K
4,Jason A. Williams “Parabolic Guy”,@GoingParabolic,2021-07-18T20:50:31.000Z,Time to spartan up. They are coming for your #...,75,39,524

In [6]:
df.dropna(inplace=True)
df.head()

,UserName,Handle,Timestamp,Text,Comments,Likes,Retweets
0,Erin Malone,@ErinEMalone,2021-07-18T23:23:20.000Z,"1. 10 weeks ago, I joined the \n@lightning\n n...",76,487,1.9K
1,Linkamus ₿ ∞/21M,@VersusTheMan,2021-07-18T23:02:42.000Z,I've bought as much #bitcoin as I can possibly...,153,37,718
2,Ben Armstrong,@Bitboy_Crypto,2021-07-18T21:50:17.000Z,The vast majority of people are crypto-aware. ...,97,113,1K
3,AirdropStar,@AirdropStario,2021-07-18T20:52:26.000Z,YUKISwap Airdrop \n\n Task: Up to 40...,170,1.7K,1.4K
4,Jason A. Williams “Parabolic Guy”,@GoingParabolic,2021-07-18T20:50:31.000Z,Time to spartan up. They are coming for your #...,75,39,524

In [7]:
df['scores'] = df['Text'].apply(lambda review: sid.polarity_scores(review))
df.head()

,UserName,Handle,Timestamp,Text,Comments,Likes,Retweets,scores
0,Erin Malone,@ErinEMalone,2021-07-18T23:23:20.000Z,"1. 10 weeks ago, I joined the \n@lightning\n n...",76,487,1.9K,"{'neg': 0.0, 'neu': 0.929, 'pos': 0.071, 'comp..."
1,Linkamus ₿ ∞/21M,@VersusTheMan,2021-07-18T23:02:42.000Z,I've bought as much #bitcoin as I can possibly...,153,37,718,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound..."
2,Ben Armstrong,@Bitboy_Crypto,2021-07-18T21:50:17.000Z,The vast majority of people are crypto-aware. ...,97,113,1K,"{'neg': 0.076, 'neu': 0.924, 'pos': 0.0, 'comp..."
3,AirdropStar,@AirdropStario,2021-07-18T20:52:26.000Z,YUKISwap Airdrop \n\n Task: Up to 40...,170,1.7K,1.4K,"{'neg': 0.037, 'neu': 0.707, 'pos': 0.255, 'co..."
4,Jason A. Williams “Parabolic Guy”,@GoingParabolic,2021-07-18T20:50:31.000Z,Time to spartan up. They are coming for your #...,75,39,524,"{'neg': 0.0, 'neu': 0.81, 'pos': 0.19, 'compou..."

In [8]:
df['compound']  = df['scores'].apply(lambda score_dict: score_dict['compound'])
df = df.drop(columns = ["scores"])
df.head()

,UserName,Handle,Timestamp,Text,Comments,Likes,Retweets,compound
0,Erin Malone,@ErinEMalone,2021-07-18T23:23:20.000Z,"1. 10 weeks ago, I joined the \n@lightning\n n...",76,487,1.9K,0.4404
1,Linkamus ₿ ∞/21M,@VersusTheMan,2021-07-18T23:02:42.000Z,I've bought as much #bitcoin as I can possibly...,153,37,718,0.0000
2,Ben Armstrong,@Bitboy_Crypto,2021-07-18T21:50:17.000Z,The vast majority of people are crypto-aware. ...,97,113,1K,-0.4215
3,AirdropStar,@AirdropStario,2021-07-18T20:52:26.000Z,YUKISwap Airdrop \n\n Task: Up to 40...,170,1.7K,1.4K,0.9402
4,Jason A. Williams “Parabolic Guy”,@GoingParabolic,2021-07-18T20:50:31.000Z,Time to spartan up. They are coming for your #...,75,39,524,0.5719

In [9]:
df['comp_score'] = df['compound'].apply(lambda c: 'pos' if c >=0 else 'neg')
df.head()

,UserName,Handle,Timestamp,Text,Comments,Likes,Retweets,compound,comp_score
0,Erin Malone,@ErinEMalone,2021-07-18T23:23:20.000Z,"1. 10 weeks ago, I joined the \n@lightning\n n...",76,487,1.9K,0.4404,pos
1,Linkamus ₿ ∞/21M,@VersusTheMan,2021-07-18T23:02:42.000Z,I've bought as much #bitcoin as I can possibly...,153,37,718,0.0000,pos
2,Ben Armstrong,@Bitboy_Crypto,2021-07-18T21:50:17.000Z,The vast majority of people are crypto-aware. ...,97,113,1K,-0.4215,neg
3,AirdropStar,@AirdropStario,2021-07-18T20:52:26.000Z,YUKISwap Airdrop \n\n Task: Up to 40...,170,1.7K,1.4K,0.9402,pos
4,Jason A. Williams “Parabolic Guy”,@GoingParabolic,2021-07-18T20:50:31.000Z,Time to spartan up. They are coming for your #...,75,39,524,0.5719,pos

In [22]:
pos_count = 0
pos_score = 0.0
neg_count = 0
neg_score = 0.0
for index, row in df.iterrows():
    if row['comp_score'] == "pos":
        pos_count = pos_count + 1
        pos_score = pos_score + (row['compound']*float(row['Comments'][:-1]))
    elif row['comp_score'] == "neg":
        neg_count = neg_count + 1
        neg_score = neg_score + ((-1*row['compound'])*float(row['Comments'][:-1]))

In [26]:
pos_count

103

In [27]:
neg_count

24

In [21]:
pos_score

528.3218499999999

In [23]:
neg_score

130.5266

In [24]:
percnt = 0.0
if pos_score > neg_score:
    percnt = pos_score/(pos_score+neg_score) * 100
elif neg_score > pos_score:
    percnt = neg_score/(pos_score + neg_score)*100

In [25]:
percnt

80.18867616672696